# Include all services you would like to run
include:
  - services/bazarr/bazarr.compose.yaml
  # - services/beszel/beszel.compose.yaml
  - services/checkrr/checkrr.compose.yaml
  - services/deluge/deluge.compose.yaml
  - services/dozzle/dozzle.compose.yaml
  - services/gluetun/gluetun.compose.yaml
  - services/homepage/homepage.compose.yaml
  - services/jellyfin/jellyfin.compose.yaml
  - services/jellyseerr/jellyseerr.compose.yaml
  - services/kavita/kavita.compose.yaml
  - services/lazylibrarian/lazylibrarian.compose.yaml
  - services/lidarr/lidarr.compose.yaml
  - services/nzbget/nzbget.compose.yaml
  - services/mylar3/mylar3.compose.yaml
  - services/overseerr/overseerr.compose.yaml
  - services/pinchflat/pinchflat.compose.yaml
  - services/plex/plex.compose.yaml
  - services/prowlarr/prowlarr.compose.yaml
  - services/qbittorrent/qbittorrent.compose.yaml
  - services/radarr/radarr.compose.yaml
  - services/sabnzbd/sabnzbd.compose.yaml
  - services/sonarr/sonarr.compose.yaml
  - services/tdarr/tdarr.compose.yaml
  - services/traefik/traefik.compose.yaml
  - services/transmission/transmission.compose.yaml

name: servarr
